"""
Django settings for Forum project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import find_dotenv, load_dotenv

load_dotenv(find_dotenv(filename='email_config.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b)j9-&b8k5vga)ai2m)id9qk478@3)ky=yzhwxwm$6ehjt+e58'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

SITE_ID = 1


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'django_summernote',
    'announcement.app.AnnounceConfig',
    'main',
    'livechat',
    'profile.app.ProfileConfig',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Forum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Forum.wsgi.application'

# CELERY
CELERY_BROKER_URL = 'redis://redis:6379'
CELERY_RESULT_BACKEND = 'redis://redis:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# LOGIN
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


# EMAIL
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = os.environ.get('LOGIN')
EMAIL_HOST_PASSWORD = os.environ.get('PASSWORD')
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = f'{os.environ.get("LOGIN")}@yandex.ru'

# REDACTOR
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
X_FRAME_OPTIONS = 'SAMEORIGIN'
SUMMERNOTE_THEME = 'bs4'
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'summernote': {
        'width': '100%',
    }
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Samara'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'style': '{',
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
        'warning': {
            'format': '%(levelname)s %(pathname)s %(message)s'
        },
        'err&crit': {
            'format': '%(levelname)s %(pathname)s %(exc_info)s %(message)s'
        },
        'general': {
            'format': '%(asctime)s - %(levelname)s - %(module)s - %(message)s'
        },
        'errors': {
            'format': '%(asctime)s - %(levelname)s - %(message)s - %(pathname)s - %(exc_info)s'
        },
        'errors_mail': {
            'format': '%(asctime)s - %(levelname)s - %(message)s - %(pathname)s'
        }
    },
    'filters': {
        'debug': {'()': 'Forum.log_filter.LevelDebug'},
        'info': {'()': 'Forum.log_filter.LevelInfo'},
        'warning': {'()': 'Forum.log_filter.LevelWarning'},
        'error': {'()': 'Forum.log_filter.LevelError'},
        'critical': {'()': 'Forum.log_filter.LevelCritical'},
        "debug_true": {"()": "django.utils.log.RequireDebugTrue"},
        "debug_false": {"()": "django.utils.log.RequireDebugFalse"}
    },
    'handlers': {
        'console_debug': {
            'filters': ['debug', 'debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'console_info': {
            'filters': ['info', 'debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'console_warn': {
            'filters': ['warning', 'debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'warning'
        },
        'console_err&crit': {
            'filters': ['error', 'critical', 'debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'err&crit'
        },
        'general': {
            'filters': ['debug_false'],
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': f'{os.path.join(BASE_DIR, "logs")}/general.log',
            'formatter': 'general'
        },
        'errors': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': f'{os.path.join(BASE_DIR, "logs")}/errors.log',
            'formatter': 'errors'
        },
        'security': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': f'{os.path.join(BASE_DIR, "logs")}/security.log',
            'formatter': 'general'
        },
        'mail_admin': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'errors_mail'
        }
    },
    'loggers': {
        'django': {
            'handlers': [
                'console_debug',
                # 'console_info',
                # 'console_warn',
                'console_err&crit',
                'general'
            ],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['errors', 'mail_admin'],
            'propagate': True
        },
        'django.server': {
            'handlers': ['errors', 'mail_admin'],
            'propagate': True
        },
        'django.template': {
            'handlers': ['errors'],
            'propagate': True
        },
        'django.db.backends': {
            'handlers': ['errors'],
            'propagate': True
        },
        'django.security': {
            'handlers': ['security'],
            'propagate': True
        },
    }
}